version: "3.9"

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "flaskuser", "-pflaskpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./Back
      dockerfile: ../deploy/backend.Dockerfile
    restart: unless-stopped
    working_dir: /app/core
    command: >-
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    network_mode: "service:db"
    volumes:
      - media_data:/app/core/media
      - static_data:/app/core/static

volumes:
  db_data:
  media_data:
  static_data: