# Generated by Django 5.2.12 on 2026-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
